### ISSUE TITLE
I created a similar app and got ERROR 500.

### ISSUE THREAD

**Issue by arthtyagi** [christiannageby/facemash#2]

**Comment by christiannageby** [comment]
The app is written in python2.7 and will need to be updated to 3.7 before deployment.
If you can tell me wich exception you got i can investigate further.

**Comment by arthtyagi** [comment]
2020-02-20T17:02:01.189132+00:00 app[api]: Deploy a9c9fca3 by user arthtyagi7@gmail.com
2020-02-20T17:02:01.189132+00:00 app[api]: Release v16 created by user arthtyagi7@gmail.com
2020-02-20T17:02:04.593926+00:00 heroku[web.1]: Starting process with command `gunicorn facemash:app`
2020-02-20T17:02:07.089297+00:00 heroku[web.1]: State changed from starting to up
2020-02-20T17:02:06.841315+00:00 app[web.1]: [2020-02-20 17:02:06 +0000] [4] [INFO] Starting gunicorn 20.0.4
2020-02-20T17:02:06.841845+00:00 app[web.1]: [2020-02-20 17:02:06 +0000] [4] [INFO] Listening at: http://0.0.0.0:53881 (                                                                                         4)
2020-02-20T17:02:06.841946+00:00 app[web.1]: [2020-02-20 17:02:06 +0000] [4] [INFO] Using worker: sync
2020-02-20T17:02:06.845830+00:00 app[web.1]: [2020-02-20 17:02:06 +0000] [10] [INFO] Booting worker with pid: 10                                                                                                 2020-02-20T17:02:06.848865+00:00 app[web.1]: [2020-02-20 17:02:06 +0000] [11] [INFO] Booting worker with pid: 11                                                                                                 2020-02-20T17:02:09.000000+00:00 app[api]: Build succeeded
2020-02-20T17:02:13.698030+00:00 app[web.1]: [2020-02-20 17:02:13,695] ERROR in app: Exception on / [GET]
2020-02-20T17:02:13.698047+00:00 app[web.1]: Traceback (most recent call last):
2020-02-20T17:02:13.698078+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 2                                                                                         446, in wsgi_app
2020-02-20T17:02:13.698080+00:00 app[web.1]: response = self.full_dispatch_request()
2020-02-20T17:02:13.698082+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1                                                                                         951, in full_dispatch_request
2020-02-20T17:02:13.698082+00:00 app[web.1]: rv = self.handle_user_exception(e)
2020-02-20T17:02:13.698083+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1                                                                                         820, in handle_user_exception
2020-02-20T17:02:13.698083+00:00 app[web.1]: reraise(exc_type, exc_value, tb)
2020-02-20T17:02:13.698094+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/flask/_compat.py", li                                                                                         ne 39, in reraise
2020-02-20T17:02:13.698096+00:00 app[web.1]: raise value
2020-02-20T17:02:13.698097+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1                                                                                         949, in full_dispatch_request
2020-02-20T17:02:13.698097+00:00 app[web.1]: rv = self.dispatch_request()
2020-02-20T17:02:13.698097+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1                                                                                         935, in dispatch_request
2020-02-20T17:02:13.698099+00:00 app[web.1]: return self.view_functions[rule.endpoint](**req.view_args)
2020-02-20T17:02:13.698099+00:00 app[web.1]: File "/app/facemash.py", line 40, in home
2020-02-20T17:02:13.698100+00:00 app[web.1]: index = random.sample(range(0, len(images)), 2)
2020-02-20T17:02:13.698101+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/random.py", line 320, in sample                                                                                             2020-02-20T17:02:13.698102+00:00 app[web.1]: raise ValueError("Sample larger than population or is negative")
2020-02-20T17:02:13.698110+00:00 app[web.1]: ValueError: Sample larger than population or is negative
2020-02-20T17:02:13.699932+00:00 app[web.1]: 10.186.202.203 - - [20/Feb/2020:17:02:13 +0000] "GET / HTTP/1.1" 500 290 "h                                                                                         ttps://dashboard.heroku.com/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/8                                                                                         0.0.3987.106 Safari/537.36 Edg/80.0.361.54"
2020-02-20T17:02:13.700086+00:00 heroku[router]: at=info method=GET path="/" host=facemashlocal.herokuapp.com request_id                                                                                         =dc6bbf9a-c337-4519-a5f6-594a41ea342a fwd="122.161.40.7" dyno=web.1 connect=2ms service=8ms status=500 bytes=470 protoco                                                                                         l=https
2020-02-20T17:07:48.073053+00:00 app[web.1]: [2020-02-20 17:07:48,072] ERROR in app: Exception on / [GET]
2020-02-20T17:07:48.073083+00:00 app[web.1]: Traceback (most recent call last):
2020-02-20T17:07:48.073084+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 2                                                                                         446, in wsgi_app
2020-02-20T17:07:48.073085+00:00 app[web.1]: response = self.full_dispatch_request()
2020-02-20T17:07:48.073092+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1                                                                                         951, in full_dispatch_request
2020-02-20T17:07:48.073093+00:00 app[web.1]: rv = self.handle_user_exception(e)
2020-02-20T17:07:48.073093+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1                                                                                         820, in handle_user_exception
2020-02-20T17:07:48.073094+00:00 app[web.1]: reraise(exc_type, exc_value, tb)
2020-02-20T17:07:48.073094+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/flask/_compat.py", li                                                                                         ne 39, in reraise
2020-02-20T17:07:48.073096+00:00 app[web.1]: raise value
2020-02-20T17:07:48.073096+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1                                                                                         949, in full_dispatch_request
2020-02-20T17:07:48.073096+00:00 app[web.1]: rv = self.dispatch_request()
2020-02-20T17:07:48.073097+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1                                                                                         935, in dispatch_request
2020-02-20T17:07:48.073097+00:00 app[web.1]: return self.view_functions[rule.endpoint](**req.view_args)
2020-02-20T17:07:48.073098+00:00 app[web.1]: File "/app/facemash.py", line 40, in home
2020-02-20T17:07:48.073098+00:00 app[web.1]: index = random.sample(range(0, len(images)), 2)
2020-02-20T17:07:48.073099+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/random.py", line 320, in sample                                                                                             2020-02-20T17:07:48.073100+00:00 app[web.1]: raise ValueError("Sample larger than population or is negative")
2020-02-20T17:07:48.073107+00:00 app[web.1]: ValueError: Sample larger than population or is negative
2020-02-20T17:07:48.073798+00:00 app[web.1]: 10.143.30.109 - - [20/Feb/2020:17:07:48 +0000] "GET / HTTP/1.1" 500 290 "ht                                                                                         tps://dashboard.heroku.com/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80                                                                                         .0.3987.106 Safari/537.36 Edg/80.0.361.54"
2020-02-20T17:07:48.075064+00:00 heroku[router]: at=info method=GET path="/" host=facemashlocal.herokuapp.com request_id                                                                                         =d781229e-69fa-43f0-93c5-5ccaa193a690 fwd="122.161.40.7" dyno=web.1 connect=1ms service=2ms status=500 bytes=470 protoco                                                                                         l=https
2020-02-20T17:24:25.000000+00:00 app[api]: Build started by user arthtyagi7@gmail.com
2020-02-20T17:24:54.069306+00:00 heroku[web.1]: Restarting
2020-02-20T17:24:54.071984+00:00 heroku[web.1]: State changed from up to starting
2020-02-20T17:24:53.757174+00:00 app[api]: Release v17 created by user arthtyagi7@gmail.com
2020-02-20T17:24:53.757174+00:00 app[api]: Deploy 8e7b0981 by user arthtyagi7@gmail.com
2020-02-20T17:24:55.053397+00:00 heroku[web.1]: Stopping all processes with SIGTERM
2020-02-20T17:24:55.064002+00:00 app[web.1]: [2020-02-20 17:24:55 +0000] [11] [INFO] Worker exiting (pid: 11)
2020-02-20T17:24:55.064119+00:00 app[web.1]: [2020-02-20 17:24:55 +0000] [10] [INFO] Worker exiting (pid: 10)
2020-02-20T17:24:55.064764+00:00 app[web.1]: [2020-02-20 17:24:55 +0000] [4] [INFO] Handling signal: term
2020-02-20T17:24:55.165974+00:00 app[web.1]: [2020-02-20 17:24:55 +0000] [4] [INFO] Shutting down: Master
2020-02-20T17:24:55.279608+00:00 heroku[web.1]: Process exited with status 0
2020-02-20T17:24:57.824602+00:00 heroku[web.1]: Starting process with command `gunicorn facemash:app`
2020-02-20T17:25:00.568741+00:00 heroku[web.1]: State changed from starting to up
2020-02-20T17:25:00.138693+00:00 app[web.1]: [2020-02-20 17:25:00 +0000] [4] [INFO] Starting gunicorn 20.0.4
2020-02-20T17:25:00.139419+00:00 app[web.1]: [2020-02-20 17:25:00 +0000] [4] [INFO] Listening at: http://0.0.0.0:13060 (                                                                                         4)
2020-02-20T17:25:00.139539+00:00 app[web.1]: [2020-02-20 17:25:00 +0000] [4] [INFO] Using worker: sync
2020-02-20T17:25:00.144918+00:00 app[web.1]: [2020-02-20 17:25:00 +0000] [10] [INFO] Booting worker with pid: 10                                                                                                 2020-02-20T17:25:00.223020+00:00 app[web.1]: [2020-02-20 17:25:00 +0000] [11] [INFO] Booting worker with pid: 11                                                                                                 2020-02-20T17:25:02.000000+00:00 app[api]: Build succeeded
2020-02-20T17:31:05.412889+00:00 heroku[router]: at=info method=GET path="/" host=facemashlocal.herokuapp.com request_id                                                                                         =9415c827-9061-4e06-8844-00bdcff24389 fwd="122.161.40.7" dyno=web.1 connect=0ms service=7ms status=500 bytes=470 protoco                                                                                         l=https
2020-02-20T17:31:05.411128+00:00 app[web.1]: [2020-02-20 17:31:05,408] ERROR in app: Exception on / [GET]
2020-02-20T17:31:05.411137+00:00 app[web.1]: Traceback (most recent call last):
2020-02-20T17:31:05.411139+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 2                                                                                         446, in wsgi_app
2020-02-20T17:31:05.411139+00:00 app[web.1]: response = self.full_dispatch_request()
2020-02-20T17:31:05.411148+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1                                                                                         951, in full_dispatch_request
2020-02-20T17:31:05.411149+00:00 app[web.1]: rv = self.handle_user_exception(e)
2020-02-20T17:31:05.411149+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1                                                                                         820, in handle_user_exception
2020-02-20T17:31:05.411149+00:00 app[web.1]: reraise(exc_type, exc_value, tb)
2020-02-20T17:31:05.411150+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
2020-02-20T17:31:05.411151+00:00 app[web.1]: raise value
2020-02-20T17:31:05.411151+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
2020-02-20T17:31:05.411152+00:00 app[web.1]: rv = self.dispatch_request()
2020-02-20T17:31:05.411152+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
2020-02-20T17:31:05.411152+00:00 app[web.1]: return self.view_functions[rule.endpoint](**req.view_args)
2020-02-20T17:31:05.411153+00:00 app[web.1]: File "/app/facemash.py", line 40, in home
2020-02-20T17:31:05.411153+00:00 app[web.1]: index = random.sample(range(0, len(images)), 2)
2020-02-20T17:31:05.411154+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/random.py", line 320, in sample
2020-02-20T17:31:05.411154+00:00 app[web.1]: raise ValueError("Sample larger than population or is negative")
2020-02-20T17:31:05.411307+00:00 app[web.1]: ValueError: Sample larger than population or is negative
2020-02-20T17:31:05.413105+00:00 app[web.1]: 10.47.238.174 - - [20/Feb/2020:17:31:05 +0000] "GET / HTTP/1.1" 500 290 "https://dashboard.heroku.com/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.106 Safari/537.36 Edg/80.0.361.54"
2020-02-20T18:05:01.304902+00:00 heroku[web.1]: Idling
2020-02-20T18:05:01.309014+00:00 heroku[web.1]: State changed from up to down
2020-02-20T18:05:02.525012+00:00 app[web.1]: [2020-02-20 18:05:02 +0000] [10] [INFO] Worker exiting (pid: 10)
2020-02-20T18:05:02.526524+00:00 app[web.1]: [2020-02-20 18:05:02 +0000] [4] [INFO] Handling signal: term
2020-02-20T18:05:02.530658+00:00 app[web.1]: [2020-02-20 18:05:02 +0000] [11] [INFO] Worker exiting (pid: 11)
2020-02-20T18:05:02.496243+00:00 heroku[web.1]: Stopping all processes with SIGTERM
2020-02-20T18:05:02.830052+00:00 app[web.1]: [2020-02-20 18:05:02 +0000] [4] [INFO] Shutting down: Master
2020-02-20T18:05:02.980918+00:00 heroku[web.1]: Process exited with status 0
PS C:\Users\Arth Tyagi\documents\github\facemash> heroku logs -a facemashlocal
2020-02-20T17:02:01.189132+00:00 app[api]: Deploy a9c9fca3 by user arthtyagi7@gmail.com
2020-02-20T17:02:01.189132+00:00 app[api]: Release v16 created by user arthtyagi7@gmail.com
2020-02-20T17:02:04.593926+00:00 heroku[web.1]: Starting process with command `gunicorn facemash:app`
2020-02-20T17:02:07.089297+00:00 heroku[web.1]: State changed from starting to up
2020-02-20T17:02:06.841315+00:00 app[web.1]: [2020-02-20 17:02:06 +0000] [4] [INFO] Starting gunicorn 20.0.4
2020-02-20T17:02:06.841845+00:00 app[web.1]: [2020-02-20 17:02:06 +0000] [4] [INFO] Listening at: http://0.0.0.0:53881 (4)
2020-02-20T17:02:06.841946+00:00 app[web.1]: [2020-02-20 17:02:06 +0000] [4] [INFO] Using worker: sync
2020-02-20T17:02:06.845830+00:00 app[web.1]: [2020-02-20 17:02:06 +0000] [10] [INFO] Booting worker with pid: 10
2020-02-20T17:02:06.848865+00:00 app[web.1]: [2020-02-20 17:02:06 +0000] [11] [INFO] Booting worker with pid: 11
2020-02-20T17:02:09.000000+00:00 app[api]: Build succeeded
2020-02-20T17:02:13.698030+00:00 app[web.1]: [2020-02-20 17:02:13,695] ERROR in app: Exception on / [GET]
2020-02-20T17:02:13.698047+00:00 app[web.1]: Traceback (most recent call last):
2020-02-20T17:02:13.698078+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
2020-02-20T17:02:13.698080+00:00 app[web.1]: response = self.full_dispatch_request()
2020-02-20T17:02:13.698082+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
2020-02-20T17:02:13.698082+00:00 app[web.1]: rv = self.handle_user_exception(e)
2020-02-20T17:02:13.698083+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
2020-02-20T17:02:13.698083+00:00 app[web.1]: reraise(exc_type, exc_value, tb)
2020-02-20T17:02:13.698094+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
2020-02-20T17:02:13.698096+00:00 app[web.1]: raise value
2020-02-20T17:02:13.698097+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
2020-02-20T17:02:13.698097+00:00 app[web.1]: rv = self.dispatch_request()
2020-02-20T17:02:13.698097+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
2020-02-20T17:02:13.698099+00:00 app[web.1]: return self.view_functions[rule.endpoint](**req.view_args)
2020-02-20T17:02:13.698099+00:00 app[web.1]: File "/app/facemash.py", line 40, in home
2020-02-20T17:02:13.698100+00:00 app[web.1]: index = random.sample(range(0, len(images)), 2)
2020-02-20T17:02:13.698101+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/random.py", line 320, in sample
2020-02-20T17:02:13.698102+00:00 app[web.1]: raise ValueError("Sample larger than population or is negative")
2020-02-20T17:02:13.698110+00:00 app[web.1]: ValueError: Sample larger than population or is negative
2020-02-20T17:02:13.699932+00:00 app[web.1]: 10.186.202.203 - - [20/Feb/2020:17:02:13 +0000] "GET / HTTP/1.1" 500 290 "https://dashboard.heroku.com/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.106 Safari/537.36 Edg/80.0.361.54"
2020-02-20T17:02:13.700086+00:00 heroku[router]: at=info method=GET path="/" host=facemashlocal.herokuapp.com request_id=dc6bbf9a-c337-4519-a5f6-594a41ea342a fwd="122.161.40.7" dyno=web.1 connect=2ms service=8ms status=500 bytes=470 protocol=https
2020-02-20T17:07:48.073053+00:00 app[web.1]: [2020-02-20 17:07:48,072] ERROR in app: Exception on / [GET]
2020-02-20T17:07:48.073083+00:00 app[web.1]: Traceback (most recent call last):
2020-02-20T17:07:48.073084+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
2020-02-20T17:07:48.073085+00:00 app[web.1]: response = self.full_dispatch_request()
2020-02-20T17:07:48.073092+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
2020-02-20T17:07:48.073093+00:00 app[web.1]: rv = self.handle_user_exception(e)
2020-02-20T17:07:48.073093+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
2020-02-20T17:07:48.073094+00:00 app[web.1]: reraise(exc_type, exc_value, tb)
2020-02-20T17:07:48.073094+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
2020-02-20T17:07:48.073096+00:00 app[web.1]: raise value
2020-02-20T17:07:48.073096+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
2020-02-20T17:07:48.073096+00:00 app[web.1]: rv = self.dispatch_request()
2020-02-20T17:07:48.073097+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
2020-02-20T17:07:48.073097+00:00 app[web.1]: return self.view_functions[rule.endpoint](**req.view_args)
2020-02-20T17:07:48.073098+00:00 app[web.1]: File "/app/facemash.py", line 40, in home
2020-02-20T17:07:48.073098+00:00 app[web.1]: index = random.sample(range(0, len(images)), 2)
2020-02-20T17:07:48.073099+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/random.py", line 320, in sample
2020-02-20T17:07:48.073100+00:00 app[web.1]: raise ValueError("Sample larger than population or is negative")
2020-02-20T17:07:48.073107+00:00 app[web.1]: ValueError: Sample larger than population or is negative
2020-02-20T17:07:48.073798+00:00 app[web.1]: 10.143.30.109 - - [20/Feb/2020:17:07:48 +0000] "GET / HTTP/1.1" 500 290 "https://dashboard.heroku.com/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.106 Safari/537.36 Edg/80.0.361.54"
2020-02-20T17:07:48.075064+00:00 heroku[router]: at=info method=GET path="/" host=facemashlocal.herokuapp.com request_id=d781229e-69fa-43f0-93c5-5ccaa193a690 fwd="122.161.40.7" dyno=web.1 connect=1ms service=2ms status=500 bytes=470 protocol=https
2020-02-20T17:24:25.000000+00:00 app[api]: Build started by user arthtyagi7@gmail.com
2020-02-20T17:24:54.069306+00:00 heroku[web.1]: Restarting
2020-02-20T17:24:54.071984+00:00 heroku[web.1]: State changed from up to starting
2020-02-20T17:24:53.757174+00:00 app[api]: Release v17 created by user arthtyagi7@gmail.com
2020-02-20T17:24:53.757174+00:00 app[api]: Deploy 8e7b0981 by user arthtyagi7@gmail.com
2020-02-20T17:24:55.053397+00:00 heroku[web.1]: Stopping all processes with SIGTERM
2020-02-20T17:24:55.064002+00:00 app[web.1]: [2020-02-20 17:24:55 +0000] [11] [INFO] Worker exiting (pid: 11)
2020-02-20T17:24:55.064119+00:00 app[web.1]: [2020-02-20 17:24:55 +0000] [10] [INFO] Worker exiting (pid: 10)
2020-02-20T17:24:55.064764+00:00 app[web.1]: [2020-02-20 17:24:55 +0000] [4] [INFO] Handling signal: term
2020-02-20T17:24:55.165974+00:00 app[web.1]: [2020-02-20 17:24:55 +0000] [4] [INFO] Shutting down: Master
2020-02-20T17:24:55.279608+00:00 heroku[web.1]: Process exited with status 0
2020-02-20T17:24:57.824602+00:00 heroku[web.1]: Starting process with command `gunicorn facemash:app`
2020-02-20T17:25:00.568741+00:00 heroku[web.1]: State changed from starting to up
2020-02-20T17:25:00.138693+00:00 app[web.1]: [2020-02-20 17:25:00 +0000] [4] [INFO] Starting gunicorn 20.0.4
2020-02-20T17:25:00.139419+00:00 app[web.1]: [2020-02-20 17:25:00 +0000] [4] [INFO] Listening at: http://0.0.0.0:13060 (4)
2020-02-20T17:25:00.139539+00:00 app[web.1]: [2020-02-20 17:25:00 +0000] [4] [INFO] Using worker: sync
2020-02-20T17:25:00.144918+00:00 app[web.1]: [2020-02-20 17:25:00 +0000] [10] [INFO] Booting worker with pid: 10
2020-02-20T17:25:00.223020+00:00 app[web.1]: [2020-02-20 17:25:00 +0000] [11] [INFO] Booting worker with pid: 11
2020-02-20T17:25:02.000000+00:00 app[api]: Build succeeded
2020-02-20T17:31:05.412889+00:00 heroku[router]: at=info method=GET path="/" host=facemashlocal.herokuapp.com request_id=9415c827-9061-4e06-8844-00bdcff24389 fwd="122.161.40.7" dyno=web.1 connect=0ms service=7ms status=500 bytes=470 protocol=https
2020-02-20T17:31:05.411128+00:00 app[web.1]: [2020-02-20 17:31:05,408] ERROR in app: Exception on / [GET]
2020-02-20T17:31:05.411137+00:00 app[web.1]: Traceback (most recent call last):
2020-02-20T17:31:05.411139+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
2020-02-20T17:31:05.411139+00:00 app[web.1]: response = self.full_dispatch_request()
2020-02-20T17:31:05.411148+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
2020-02-20T17:31:05.411149+00:00 app[web.1]: rv = self.handle_user_exception(e)
2020-02-20T17:31:05.411149+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
2020-02-20T17:31:05.411149+00:00 app[web.1]: reraise(exc_type, exc_value, tb)
2020-02-20T17:31:05.411150+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
2020-02-20T17:31:05.411151+00:00 app[web.1]: raise value
2020-02-20T17:31:05.411151+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
2020-02-20T17:31:05.411152+00:00 app[web.1]: rv = self.dispatch_request()
2020-02-20T17:31:05.411152+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
2020-02-20T17:31:05.411152+00:00 app[web.1]: return self.view_functions[rule.endpoint](**req.view_args)
2020-02-20T17:31:05.411153+00:00 app[web.1]: File "/app/facemash.py", line 40, in home
2020-02-20T17:31:05.411153+00:00 app[web.1]: index = random.sample(range(0, len(images)), 2)
2020-02-20T17:31:05.411154+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.6/random.py", line 320, in sample
2020-02-20T17:31:05.411154+00:00 app[web.1]: raise ValueError("Sample larger than population or is negative")
2020-02-20T17:31:05.411307+00:00 app[web.1]: ValueError: Sample larger than population or is negative
2020-02-20T17:31:05.413105+00:00 app[web.1]: 10.47.238.174 - - [20/Feb/2020:17:31:05 +0000] "GET / HTTP/1.1" 500 290 "https://dashboard.heroku.com/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.106 Safari/537.36 Edg/80.0.361.54"
2020-02-20T18:05:01.304902+00:00 heroku[web.1]: Idling
2020-02-20T18:05:01.309014+00:00 heroku[web.1]: State changed from up to down
2020-02-20T18:05:02.525012+00:00 app[web.1]: [2020-02-20 18:05:02 +0000] [10] [INFO] Worker exiting (pid: 10)
2020-02-20T18:05:02.526524+00:00 app[web.1]: [2020-02-20 18:05:02 +0000] [4] [INFO] Handling signal: term
2020-02-20T18:05:02.530658+00:00 app[web.1]: [2020-02-20 18:05:02 +0000] [11] [INFO] Worker exiting (pid: 11)
2020-02-20T18:05:02.496243+00:00 heroku[web.1]: Stopping all processes with SIGTERM
2020-02-20T18:05:02.830052+00:00 app[web.1]: [2020-02-20 18:05:02 +0000] [4] [INFO] Shutting down: Master
2020-02-20T18:05:02.980918+00:00 heroku[web.1]: Process exited with status 0
PS C:\Users\Arth Tyagi\documents\github\facemash>

**Comment by christiannageby** [comment]
Well the thing is, If you look in the code there is a function that is getting all paths to the images in `static/images/` that folder is not created in this repo, don't know why might be something with .gitignore. But to help you out for now just create that folder and add images to it and it should work. 

Also feel free to post a pull request if you make it work and ill merge it :)

**Comment by arthtyagi** [comment]
i already did create the static/images folder with images.

**Comment by christiannageby** [comment]
Well then, I'll take a look at the code.
